# AMAZON
AMAZON_ACCESS_KEY = "SUA_ACCESS_KEY"
AMAZON_SECRET_KEY = "SUA_SECRET_KEY"
AMAZON_ASSOCIATE_TAG = "SEU_ID-20"
AMAZON_MARKETPLACE = "www.amazon.com.br"

# WHATSAPP
WHATSAPP_API_URL = "SUA_API"
WHATSAPP_TOKEN = "SEU_TOKEN"
WHATSAPP_PHONE = "558599999999"
